name: 'Generate SBOM YAML'
description: 'Generate SBOM (SPDX) and OpenContext artifact YAML'
branding:
  icon: 'map'
  color: 'blue'
inputs:
  upload_yaml:
    description: 'Upload OpenContext SBOM artifact YAML to release?'
    required: true
    default: 'true'
outputs:
  sbom_path:
    description: 'The path of the SBOM generated'
    value: ${{ steps.generate-sbom.outputs.fileName }} 
  sbom_url:
    description: 'The release URL where the SBOM can be downloaded from'
    value: ${{ steps.check-prereqs.outputs.sbomUrl }}
  artifact_path:
    description: 'The path of the OpenContext SBOM artifact YAML'
    value: ${{ github.workspace }}/${{ steps.generate-artifact-yaml.outputs.filename }}
  artifact_url:
    description: 'The release URL of the OpenContext SBOM artifact YAML or WORKSPACE_ARTIFACT if upload_yaml is false'
    value: ${{ steps.check-prereqs.outputs.artifactUrl }}
runs:
  using: 'composite'
  steps:
    - id: check-prereqs
      name: Check pre-requisites
      shell: bash
      run: |
        if [[ ${GITHUB_EVENT_NAME} != "release" ]]; then 
          echo "ERROR: This GitHub action only supports the release event!"
          exit 1
        fi
        artifactFile="oc-artifact-yaml.tgz"
        shortSHA=$(echo $GITHUB_SHA | head -c7)
        repoName=$(basename $GITHUB_REPOSITORY)
        sbomFilename="${repoName}-${shortSHA}-sbom-spdx.json"
        releaseHtmlUrl=$(jq -r '.release.html_url' $GITHUB_EVENT_PATH)
        releaseTag=$(basename $releaseHtmlUrl)
        sbomUrl="${releaseHtmlUrl%%/releases/*}/releases/download/${releaseTag}/${sbomFilename}"
        if [[ ${{ inputs.upload_yaml }} == "true" ]]; then
          artifactUrl="${releaseHtmlUrl%%/releases/*}/releases/download/${releaseTag}/${artifactFile}"
        else
          artifactUrl=WORKSPACE_ARTIFACT
        fi
        echo "artifactFile=${artifactFile}" >> "$GITHUB_OUTPUT"
        echo "artifactUrl=${artifactUrl}" >> "$GITHUB_OUTPUT"
        echo "sbomFilename=${sbomFilename}" >> "$GITHUB_OUTPUT"
        echo "sbomUrl=${sbomUrl}" >> "$GITHUB_OUTPUT"
    - id: generate-sbom
      name: Generate SBOM
      uses: advanced-security/sbom-generator-action@v1
    - id: upload-sbom-release
      name: Upload SBOM as release artifact
      uses: Shopify/upload-to-release@v1.0.1
      with:
        name: ${{ steps.check-prereqs.outputs.sbomFilename }}
        path: ${{ steps.generate-sbom.outputs.fileName }}
        repo-token: ${{ github.token }}
        content-type:  application/json
    - id: generate-artifact-yaml
      name: Generate OpenContext artifact YAML for SBOM
      uses: opencontextinc/create-artifact-yaml@v1.0.0
      with:
        type: sbom
        url: ${{ steps.check-prereqs.outputs.sbomUrl }}
    - id: upload-artifact-yaml-release
      name: Upload OpenContext artifact YAML as release artifact
      if: ${{ inputs.upload_yaml == 'true' }}
      uses: Shopify/upload-to-release@v1.0.1
      with:
        name: ${{ steps.check-prereqs.outputs.artifactFile }}
        path: ${{ steps.generate-artifact-yaml.outputs.filename }}
        repo-token: ${{ github.token }}
        content-type: application/gzip
    - id: upload-artifact-yaml-workspace
      name: Upload OpenContext artifact YAML as workspace artifact
      if: ${{ inputs.upload_yaml != 'true' }}
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ steps.check-prereqs.outputs.artifactFile }}
        path: ${{ steps.generate-artifact-yaml.outputs.filename }}
